MODULENAME=twapi_eventlog

!include ..\include\common.inc

OBJS  = $(OBJDIR)\eventlog.obj $(OBJDIR)\evt.obj
TCLFILES=..\tcl\eventlog.tcl ..\tcl\evt.tcl ..\tcl\winlog.tcl

!include ..\include\rules.inc
