MODULENAME=twapi_security

!include ..\include\common.inc

OBJS  = $(OBJDIR)\security.obj
TCLFILES=..\tcl\security.tcl
EXTRALIBS = $(SDKLIB)userenv.lib $(SDKLIB)credui.lib

!include ..\include\rules.inc
