MODULENAME=twapi_service

!include ..\include\common.inc

OBJS  = $(OBJDIR)\service.obj $(OBJDIR)\scm.obj
TCLFILES=..\tcl\service.tcl 

!include ..\include\rules.inc

$(OBJS): twapi_service.h

