MODULENAME=twapi_account
PREREQUISITES=twapi_security
!include ..\include\common.inc

OBJS  = $(OBJDIR)\account.obj
TCLFILES=..\tcl\accounts.tcl
EXTRALIBS = userenv.lib

!include ..\include\rules.inc
