# This file is automatically generated and will be overwritten
namespace eval twapi {
    variable version 4.0
    variable patchlevel 4.0a0
    variable package_name twapi_base
    if {$::tcl_platform(machine) eq "amd64"} {
        variable dll_base_name twapi_base64
    } else {
        variable dll_base_name twapi_base
    }
}
